development:
  adapter: async

test:
  adapter: test

production:
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: sweet_tooth_2021_production
  adapter: async
